[Definition]

# Action executed on starting jail
actionstart = 

# Action executed on stopping jail
actionstop = 

# Action executed on banning IP (Calls Python rich alert script)
actionban = python3 /etc/fail2ban/scripts/telegram_fail2ban.py --action ban --jail "<name>" --ip "<ip>" --failures "<failures>" --bantime "<bantime>"

# Action executed on unbanning IP
actionunban = python3 /etc/fail2ban/scripts/telegram_fail2ban.py --action unban --jail "<name>" --ip "<ip>" --failures "<failures>" --bantime "<bantime>"

[Init]
